select * from T_STK_INSTOCKENTRY_LK lk 
left join T_STK_INSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_RECEIVE r on r.FID=lk.FSBILLID
left join T_PUR_RECEIVEENTRY re on re.FENTRYID=lk.FSID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_RECEIVEENTRY_LK lk 
left join T_PUR_RECEIVEENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_RECEIVE t on t.FID=e.FID
left join t_PUR_POOrder r on r.FID=lk.FSBILLID
left join t_PUR_POOrderEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_SUB_REQORDER r on r.FID=lk.FSBILLID
left join T_SUB_REQORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SUB_REQORDERENTRY'

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_PUR_MRB r on r.FID=lk.FSBILLID
left join T_PUR_MRBENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_PUR_MRBENTRY'

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_PUR_REQUISITION r on r.FID=lk.FSBILLID
left join T_PUR_ReqEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where ( r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_PUR_ReqEntry'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PRD_INSTOCKENTRY_LK lk 
left join T_PRD_INSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_INSTOCK t on t.FID=e.FID
left join T_PRD_MORPT r on r.FID=lk.FSBILLID
left join T_PRD_MORPTENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PRD_MORPTENTRY_LK lk 
left join T_PRD_MORPTENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_MORPT t on t.FID=e.FID
left join T_PRD_MO r on r.FID=lk.FSBILLID
left join T_PRD_MOENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PRD_MOENTRY_LK lk 
left join T_PRD_MOENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_MO t on t.FID=e.FID
left join T_PRD_MO r on r.FID=lk.FSBILLID
left join T_PRD_MOENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>e.FSRCBILLNO or re.FSALEORDERENTRYID<>e.FSALEORDERENTRYID) and lk.FSTABLENAME='T_PRD_MOENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_PRD_MOENTRY_LK lk 
left join T_PRD_MOENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_MO t on t.FID=e.FID
left join T_SAL_ORDER r on r.FID=lk.FSBILLID
left join T_SAL_ORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>e.FSRCBILLNO or re.FENTRYID<>e.FSALEORDERENTRYID) and lk.FSTABLENAME='T_SAL_ORDERENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_PRD_MOENTRY_LK lk 
left join T_PRD_MOENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_MO t on t.FID=e.FID
left join T_PLN_FORECAST r on r.FID=lk.FSBILLID
left join T_PLN_FORECASTENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_PLN_FORECASTENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SAL_RETURNSTOCKENTRY_LK lk 
left join T_SAL_RETURNSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_RETURNSTOCK t on t.FID=e.FID
left join T_SAL_ORDER r on r.FID=lk.FSBILLID
left join T_SAL_ORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>e.FORDERNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SAL_ORDERENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SAL_RETURNSTOCKENTRY_LK lk 
left join T_SAL_RETURNSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_RETURNSTOCK t on t.FID=e.FID
left join T_SAL_OUTSTOCK r on r.FID=lk.FSBILLID
left join T_SAL_OUTSTOCKENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SAL_OUTSTOCKENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SAL_RETURNSTOCKENTRY_LK lk 
left join T_SAL_RETURNSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_RETURNSTOCK t on t.FID=e.FID
left join T_SAL_RETURNNOTICE r on r.FID=lk.FSBILLID
left join T_SAL_RETURNNOTICEENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where ( re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SAL_RETURNNOTICEENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SAL_RETURNSTOCKENTRY_LK lk 
left join T_SAL_RETURNSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_RETURNSTOCK t on t.FID=e.FID
left join T_SAL_RETURNNOTICE r on r.FID=lk.FSBILLID
left join T_SAL_RETURNNOTICEENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where ( re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SAL_RETURNNOTICEENTRY'

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SUB_RETURNMTRL_LK lk 
left join T_SUB_RETURNMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SUB_RETURNMTRLENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join T_SUB_RETURNMTRL t on t.FID=e.FID
left join T_SUB_PICKMTRL r on r.FID=lk.FSBILLID
left join T_SUB_PICKMTRLDATA re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SUB_PICKMTRLDATA'

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SUB_RETURNMTRL_LK lk 
left join T_SUB_RETURNMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SUB_RETURNMTRLENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join T_SUB_RETURNMTRL t on t.FID=e.FID
left join T_SUB_PPBOM r on r.FID=lk.FSBILLID
left join T_SUB_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SUB_PPBOMENTRY'

select t.FBILLNO,t.FSOURCEBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SAL_ORDERCHANGEENTRY_LK lk 
left join T_SAL_ORDERCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_ORDERCHANGE t on t.FID=e.FID
left join T_SAL_ORDER r on r.FID=lk.FSBILLID
left join T_SAL_ORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>t.FSOURCEBILLNO or  re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SAL_ORDERENTRY'

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SUB_REQORDERENTRY_LK lk 
left join T_SUB_REQORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SUB_REQORDERENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join T_SUB_REQORDER t on t.FID=e.FID
left join T_PRD_MO r on r.FID=lk.FSBILLID
left join T_PRD_MOENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  e1.FSRCBILLENTRYSEQ<>re.FSEQ) and lk.FSTABLENAME='T_PRD_MOENTRY'

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_SUB_PICKMTRLDATA_LK lk 
left join T_SUB_PICKMTRLDATA e on lk.FENTRYID=e.FENTRYID
left join T_SUB_PICKMTRL t on t.FID=e.FID
left join T_SUB_PPBOM r on r.FID=lk.FSBILLID
left join T_SUB_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e.FSRCBILLNO or  e.FSRCENTRYSEQ<>re.FSEQ) and lk.FSTABLENAME='T_SUB_PPBOMENTRY' order by FBILLNO,FSEQ


select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ, lk.* from T_STK_STKTRANSFERINENTRY_LK lk 
left join T_STK_STKTRANSFERINENTRY e on lk.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERINENTRY_R e1 on e1.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERIN t on t.FID=e.FID
left join T_STK_STKTRANSFERIN r on r.FID=lk.FSBILLID
left join T_STK_STKTRANSFERINENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  e1.FSRCSEQ<>re.FSEQ) and lk.FSTABLENAME='T_STK_STKTRANSFERINENTRY' order by FBILLNO,FSEQ

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSRCSEQ, lk.* from T_STK_STKTRANSFERINENTRY_LK lk 
left join T_STK_STKTRANSFERINENTRY e on lk.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERINENTRY_R e1 on e1.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERIN t on t.FID=e.FID
left join T_PRD_PPBOM r on r.FID=lk.FSBILLID
left join T_PRD_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PPBOMENTRY' order by FBILLNO,FSEQ


select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSRCSEQ, lk.* from T_STK_STKTRANSFERINENTRY_LK lk 
left join T_STK_STKTRANSFERINENTRY e on lk.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERINENTRY_R e1 on e1.FENTRYID=e.FENTRYID
left join T_STK_STKTRANSFERIN t on t.FID=e.FID
left join T_SUB_PPBOM r on r.FID=lk.FSBILLID
left join T_SUB_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or  e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SUB_PPBOMENTRY' order by FBILLNO,FSEQ

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSUBPPBOMENTRYSEQ, lk.* from T_SUB_PPBOMCHANGEENTRY_LK lk 
left join T_SUB_PPBOMCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SUB_PPBOMCHANGEENTRY_C e1 on e1.FENTRYID=e.FENTRYID
left join T_SUB_PPBOMCHANGE t on t.FID=e.FID
left join T_SUB_PPBOM r on r.FID=lk.FSBILLID
left join T_SUB_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSUBPPBOMNO or  e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SUB_PPBOMENTRY' order by FBILLNO,FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FPPBOMBILLNO, lk.* from T_PRD_PICKMTRLDATA_LK lk 
left join T_PRD_PICKMTRLDATA e on lk.FENTRYID=e.FENTRYID
left join T_PRD_PICKMTRL t on t.FID=e.FID
left join T_PRD_PPBOM r on r.FID=lk.FSBILLID
left join T_PRD_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e.FSRCBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PPBOMENTRY' order by FBILLNO,FSEQ


select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq, lk.* from T_SAL_OUTSTOCKENTRY_LK lk 
left join T_SAL_OUTSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCKENTRY_R e1 on e1.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCK t on t.FID=e.FID
left join T_SAL_ORDER r on r.FID=lk.FSBILLID
left join T_SAL_ORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (r.FBILLNO<>e1.FSRCBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SAL_ORDERENTRY' order by FBILLNO,FSEQ

----------------------------------------------------------------------------------------------------------------------------------------------------------
select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq, lk.* from T_SAL_OUTSTOCKENTRY_LK lk 
left join T_SAL_OUTSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCKENTRY_R e1 on e1.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCK t on t.FID=e.FID
left join T_SAL_DELIVERYNOTICE r on r.FID=lk.FSBILLID
left join T_SAL_DELIVERYNOTICEENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e1.FSRCBILLNO<>r.FBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SAL_DELIVERYNOTICEENTRY' order by FBILLNO,FSEQ
----------------------------------------------------------------------------------------------------------------------------------------------------------
select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCENTRYSEQ srcseq,
lk.* from T_PRD_RETURNMTRLENTRY_LK lk 
left join T_PRD_RETURNMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_RETURNMTRL t on t.FID=e.FID
left join T_PRD_PICKMTRL r on r.FID=lk.FSBILLID
left join T_PRD_PICKMTRLDATA re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PICKMTRLDATA' order by FBILLNO,e.FSEQ
--e.FSRCBILLNO<>r.FBILLNO or 

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCENTRYSEQ srcseq,
lk.* from T_PRD_RETURNMTRLENTRY_LK lk 
left join T_PRD_RETURNMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_RETURNMTRL t on t.FID=e.FID
left join T_PRD_FEEDMTRL r on r.FID=lk.FSBILLID
left join T_PRD_FEEDMTRLDATA re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_FEEDMTRLDATA' order by FBILLNO,e.FSEQ


select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCENTRYSEQ srcseq,
lk.* from T_PRD_RETURNMTRLENTRY_LK lk 
left join T_PRD_RETURNMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PRD_RETURNMTRL t on t.FID=e.FID
left join T_PRD_PPBOM r on r.FID=lk.FSBILLID
left join T_PRD_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PPBOMENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e1.FPPBOMNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FPPBOMENTRYSEQ srcseq,
lk.* from  T_PRD_PPBOMCHANGEENTRY_LK lk 
left join  T_PRD_PPBOMCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PRD_PPBOMCHANGEENTRY_C e1 on e1.FENTRYID=e.FENTRYID
left join  T_PRD_PPBOMCHANGE t on t.FID=e.FID
left join T_PRD_PPBOM r on r.FID=lk.FSBILLID
left join T_PRD_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e1.FPPBOMNO<>r.FBILLNO or e1.FPPBOMENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PPBOMENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e1.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSRCENTRYSEQ srcseq,
lk.* from  T_QM_INSPECTBILLENTRY_LK lk 
left join  T_QM_INSPECTBILLENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILLENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILL t on t.FID=e.FID
left join T_PRD_MORPT r on r.FID=lk.FSBILLID
left join T_PRD_MORPTENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e1.FMATERIALID
where  (e1.FSRCBILLNO<>r.FBILLNO or e1.FSRCENTRYSEQ<>re.FSEQ or e1.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_MORPTENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e1.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSRCENTRYSEQ srcseq,
lk.* from  T_QM_INSPECTBILLENTRY_LK lk 
left join  T_QM_INSPECTBILLENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILLENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILL t on t.FID=e.FID
left join T_PUR_Receive r on r.FID=lk.FSBILLID
left join T_PUR_ReceiveEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e1.FMATERIALID
where  (e1.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PUR_ReceiveEntry' order by FBILLNO,e.FSEQ
--e1.FSRCBILLNO<>r.FBILLNO or e1.FSRCENTRYSEQ<>re.FSEQ or 

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e1.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,e1.FSRCENTRYSEQ srcseq,
lk.* from  T_QM_INSPECTBILLENTRY_LK lk 
left join  T_QM_INSPECTBILLENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILLENTRY_A e1 on e1.FENTRYID=e.FENTRYID
left join  T_QM_INSPECTBILL t on t.FID=e.FID
left join T_QM_INSPECTBILL r on r.FID=lk.FSBILLID
left join T_QM_INSPECTBILLENTRY_A re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e1.FMATERIALID
where  (e1.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_QM_INSPECTBILLENTRY' order by FBILLNO,e.FSEQ
--e1.FSRCBILLNO<>r.FBILLNO or e1.FSRCENTRYSEQ<>re.FSEQ or 

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FORDERSEQ srcseq,
lk.* from  T_SAL_DELIVERYNOTICEENTRY_LK lk 
left join  T_SAL_DELIVERYNOTICEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_SAL_DELIVERYNOTICE t on t.FID=e.FID
left join T_SAL_ORDER r on r.FID=lk.FSBILLID
left join T_SAL_ORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  ( e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SAL_ORDERENTRY' order by FBILLNO,e.FSEQ


select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e1.FSRCENTRYSEQ srcseq,
lk.* from  T_PRD_RESTOCKENTRY_LK lk 
left join  T_PRD_RESTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PRD_RESTOCKENTRY_A e1 on lk.FENTRYID=e1.FENTRYID
left join  T_PRD_RESTOCK t on t.FID=e.FID
left join T_PRD_INSTOCK r on r.FID=lk.FSBILLID
left join T_PRD_INSTOCKENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  ( e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_INSTOCKENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCENTRYSEQ srcseq,
lk.* from   T_SUB_FEEDMTRLENTRY_LK lk 
left join   T_SUB_FEEDMTRLENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_SUB_FEEDMTRL t on t.FID=e.FID
left join T_SUB_PPBOM r on r.FID=lk.FSBILLID
left join T_SUB_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SUB_PPBOMENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCBILLENTRYSEQ srcseq,
lk.* from   T_PRD_MOCHANGEENTRY_LK lk 
left join   T_PRD_MOCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PRD_MOCHANGE t on t.FID=e.FID
left join T_PRD_MO r on r.FID=lk.FSBILLID
left join T_PRD_MOENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCBILLENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_MOENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCBILLENTRYSEQ srcseq,
lk.* from   T_SUB_REQCHANGEENTRY_LK lk 
left join   T_SUB_REQCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_SUB_REQCHANGE t on t.FID=e.FID
left join T_SUB_REQORDER r on r.FID=lk.FSBILLID
left join T_SUB_REQORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCBILLENTRYSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SUB_REQORDERENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e1.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,
lk.* from   T_SAL_ORDERENTRY_LK lk 
left join   T_SAL_ORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join   T_SAL_ORDERENTRY_R e1 on lk.FENTRYID=e1.FENTRYID
left join  T_SAL_ORDER t on t.FID=e.FID
left join T_PLN_FORECAST r on r.FID=lk.FSBILLID
left join T_PLN_FORECASTENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e1.FSRCBILLNO<>r.FBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PLN_FORECASTENTRY' order by FBILLNO,e.FSEQ


select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,
lk.* from   T_PRD_FEEDMTRLDATA_LK lk 
left join   T_PRD_FEEDMTRLDATA e on lk.FENTRYID=e.FENTRYID
left join  T_PRD_FEEDMTRL t on t.FID=e.FID
left join T_PRD_PPBOM r on r.FID=lk.FSBILLID
left join T_PRD_PPBOMENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_PPBOMENTRY' order by FBILLNO,e.FSEQ


select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,
lk.* from   T_PRD_FEEDMTRLDATA_LK lk 
left join   T_PRD_FEEDMTRLDATA e on lk.FENTRYID=e.FENTRYID
left join  T_PRD_FEEDMTRL t on t.FID=e.FID
left join T_PRD_RETURNMTRL r on r.FID=lk.FSBILLID
left join T_PRD_RETURNMTRLENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PRD_RETURNMTRLENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FOFBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,
lk.* from   T_PUR_POCHANGEENTRY_LK lk 
left join   T_PUR_POCHANGEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PUR_POCHANGE t on t.FID=e.FID
left join t_PUR_POOrder r on r.FID=lk.FSBILLID
left join t_PUR_POOrderEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FOFBILLNO<>r.FBILLNO or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='t_PUR_POOrderEntry' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCSEQ srcsql,
lk.* from   T_PUR_MRBENTRY_LK lk 
left join   T_PUR_MRBENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PUR_MRB t on t.FID=e.FID
left join T_STK_INSTOCK r on r.FID=lk.FSBILLID
left join T_STK_INSTOCKENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_STK_INSTOCKENTRY' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCSEQ srcsql,
lk.* from   T_PUR_MRBENTRY_LK lk 
left join   T_PUR_MRBENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PUR_MRB t on t.FID=e.FID
left join T_PUR_Receive r on r.FID=lk.FSBILLID
left join T_PUR_ReceiveEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PUR_ReceiveEntry' order by FBILLNO,e.FSEQ

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,e.FSRCSEQ srcsql,
lk.* from   T_PUR_MRBENTRY_LK lk 
left join   T_PUR_MRBENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_PUR_MRB t on t.FID=e.FID
left join T_PUR_MRAPP r on r.FID=lk.FSBILLID
left join T_PUR_MRAPPENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or e.FSRCSEQ<>re.FSEQ or e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_PUR_MRAPPENTRY' order by FBILLNO,e.FSEQ


select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm,e.FSEQ,re.FSEQ scr_seq,
lk.* from   T_SAL_RETURNNOTICEENTRY_LK lk 
left join   T_SAL_RETURNNOTICEENTRY e on lk.FENTRYID=e.FENTRYID
left join  T_SAL_RETURNNOTICE t on t.FID=e.FID
left join T_SAL_OUTSTOCK r on r.FID=lk.FSBILLID
left join T_SAL_OUTSTOCKENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where  (e.FSRCBILLNO<>r.FBILLNO or  e.FMATERIALID<>re.FMATERIALID) and lk.FSTABLENAME='T_SAL_OUTSTOCKENTRY' order by FBILLNO,e.FSEQ





