select * from T_PUR_RECEIVEENTRY e
inner join T_PUR_RECEIVE t on e.FID=t.FID
where FBILLNO='CGSL190831132'



update T_STK_INSTOCKENTRY_LK set FSBILLID=152304 ,FSID=232491 where FLINKID=236044
update T_STK_INSTOCKENTRY_LK set FSBILLID=152316 ,FSID=232541 where FLINKID=236053
update T_STK_INSTOCKENTRY_LK set FSBILLID=152317 ,FSID=232542 where FLINKID=236054
update T_STK_INSTOCKENTRY_LK set FSBILLID=152318 ,FSID=232543 where FLINKID=236055

select * from T_STK_INSTOCKENTRY_LK lk 
left join T_STK_INSTOCKENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_RECEIVE r on r.FID=lk.FSBILLID
left join T_PUR_RECEIVEENTRY re on re.FENTRYID=lk.FSID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,e.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_RECEIVEENTRY_LK lk 
left join T_PUR_RECEIVEENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_RECEIVE t on t.FID=e.FID
left join t_PUR_POOrder r on r.FID=lk.FSBILLID
left join t_PUR_POOrderEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where r.FBILLNO<>e.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_SUB_REQORDER r on r.FID=lk.FSBILLID
left join T_SUB_REQORDERENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_SUB_REQORDERENTRY'

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_PUR_MRB r on r.FID=lk.FSBILLID
left join T_PUR_MRBENTRY re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where (r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_PUR_MRBENTRY'

select t.FBILLNO,er.FSRCBILLNO tn,r.FBILLNO fn,e.FMATERIALID tm,mat.FNUMBER,re.FMATERIALID fm, lk.* from T_PUR_POORDERENTRY_LK lk 
left join T_PUR_POORDERENTRY_R er on lk.FENTRYID=er.FENTRYID 
left join T_PUR_POORDERENTRY e on lk.FENTRYID=e.FENTRYID
left join T_PUR_POORDER t on t.FID=e.FID
left join T_PUR_REQUISITION r on r.FID=lk.FSBILLID
left join T_PUR_ReqEntry re on re.FENTRYID=lk.FSID
left join T_BD_MATERIAL mat on mat.FMATERIALID=e.FMATERIALID
where ( r.FBILLNO<>er.FSRCBILLNO or re.FMATERIALID<>e.FMATERIALID) and lk.FSTABLENAME='T_PUR_ReqEntry'


select distinct FSTABLENAME from T_PUR_POORDERENTRY_LK