select * into T_BAS_SYSTEMPROFILEchltmp from T_BAS_SYSTEMPROFILE where FCATEGORY='cb'

update T_BAS_SYSTEMPROFILE set FVALUE='2019' where FCATEGORY='cb' and FKEY='StartYear'
update T_BAS_SYSTEMPROFILE set FVALUE='1' where FCATEGORY='cb' and FKEY='StartPeriod'
update T_BAS_SYSTEMPROFILE set FVALUE='2019-01-01' where FCATEGORY='cb' and FKEY='StartDate'
update T_BAS_SYSTEMPROFILE set FVALUE='2019-01-01' where FCATEGORY='cb' and FKEY='CurrentPeriodStartDate'
update T_BAS_SYSTEMPROFILE set FVALUE='2019-01-31' where FCATEGORY='cb' and FKEY='CurrentPeriodEndDate'

select * from T_BAS_SYSTEMPROFILE where FCATEGORY='hs'
select * from T_BAS_SYSTEMPROFILE where FCATEGORY='cb'

--修改期初付款单的来源系统
update  T_AP_PAYBILL set FSOURCESYSTEM=0 where FISINIT=1 and FSOURCESYSTEM<>0

--QTYFD180930031反审核失败,删除流程实例中相关的数据
delete a from T_BF_INSTANCEAMOUNT a join  T_BF_INSTANCEENTRY b on a.FROUTEID=b.FROUTEID and b.FINSTANCEID='5bdae9a18f511f'
delete from  T_BF_INSTANCEENTRY where FINSTANCEID='5bdae9a18f511f'
delete from  T_BF_INSTANCE where FINSTANCEID='5bdae9a18f511f'
--期初应付单修改生成方式,修改为非核销产生
update T_AP_PAYABLE set FBYVERIFY=0 where FISINIT=1 

--期初收款退款
select * from T_AR_REFUNDBILL where FISINIT=1
--期初收款单

--账簿启用期间Xiugai
select * from T_BD_ACCOUNTBOOK 


update T_BD_ACCOUNTBOOK set FSTARTYEAR=2019,FSTARTPERIOD=1,FYEARANDPERIOD='2019.1' where FBOOKID=167435

select * from T_BAS_SYSTEMPROFILE where FCATEGORY='gl' and fkey in ('StartDate','StartPeriod','StartYear') and FACCOUNTBOOKID=167435

update T_BAS_SYSTEMPROFILE set FVALUE='2019-01-01' where FCATEGORY='gl' and FKEY='StartDate' and FACCOUNTBOOKID=167435
update T_BAS_SYSTEMPROFILE set FVALUE='1' where FCATEGORY='gl' and FKEY='StartPeriod' and FACCOUNTBOOKID=167435
update T_BAS_SYSTEMPROFILE set FVALUE='2019' where FCATEGORY='gl' and FKEY='StartYear' and FACCOUNTBOOKID=167435



select count(1) from T_BF_INSTANCEENTRYHIS    --1791022
select count(1) from T_BF_ARCHIVEFILES     --0
select count(1) from T_BF_INSTENTRYBACKUP     --0 

---其他应付QTYFD180930031
select * from T_AP_OTHERPAYABLE where fbillno='QTYFD180930031'
select * from T_AP_OTHERPAYABLEENTRY where fid=100047

select * from T_BF_INSTANCEENTRY where fsid=100048 and  FSTABLENAME='T_AP_OTHERPAYABLEENTRY'
select * from T_BF_INSTANCEENTRY where FTID=100048 and  FTTABLENAME='T_AP_OTHERPAYABLEENTRY'

select * from T_BF_INSTANCEENTRYHIS where  FSID=100048  and FSTABLEID=4103 
select * from T_BF_INSTANCEENTRYHIS where  FTID=100048  and FTTABLEID=4103 

select * from T_BF_INSTANCEAMOUNTHIS where FROUTEID IN (select FROUTEID from T_BF_INSTANCEENTRYHIS where FINSTANCEID='5bdae9a18f511f')
select * from T_BF_INSTANCEENTRYHIS where FINSTANCEID='5bdae9a18f511f'
select * from T_BF_INSTANCEHIS where FINSTANCEID='5bdae9a18f511f'


select * from T_BF_TABLEDEFINE where FTABLENUMBER='T_AP_OTHERPAYABLEENTRY'
select * from T_BF_TABLEDEFINE where FSEQ=4057 

select * from  T_IV_PUREXPINVENTRY where FENTRYID=100003  


DELETE from T_BF_INSTANCEAMOUNTHIS where FROUTEID IN (select FROUTEID from T_BF_INSTANCEENTRYHIS where FINSTANCEID='5bdae9a18f511f')
DELETE from T_BF_INSTANCEENTRYHIS where FINSTANCEID='5bdae9a18f511f'
DELETE from T_BF_INSTANCEHIS where FINSTANCEID='5bdae9a18f511f'



select FSOURCESYSTEM,* from T_AP_PAYBILL  where fbillno in ('FKD190115012' ,'FKD190115013','FKD190115014','FKD00000333')
update  T_AP_PAYBILL set FSOURCESYSTEM=0   where fbillno in ('FKD190115012' ,'FKD190115013','FKD190115014','FKD00000333')

select * from  T_AP_PAYBILL a join T_AP_PAYBILLENTRY b on a.fid=b.fid  and a.FBILLNO in ('FKD190111012','FKD190111014')

select c.* from  T_AP_PAYBILL a join T_AP_PAYBILLSRCENTRY b on a.fid=b.fid  and a.FBILLNO in ('FKD190111012','FKD190111014')
join   T_AP_PAYBILLSRCENTRY_LK c on b.FENTRYID=c.FENTRYID  


select * from T_AP_PAYBILLSRCENTRY_LK 

select * from T_AP_PAYBILLENTRY where fid=103591   --104727
select * from T_AP_PAYBILLSRCENTRY where fid=103591   --104411
select top 1000 * from T_BF_INSTANCESNAP where FCID like 'AP_PAYBILL%'
select top 1000 * from T_BF_INSTANCESNAP where FCID like 'AP_PAYBILL%'

select  * from T_BF_INSTANCESNAP where FCID in ('AP_PAYBILL,FPAYBILLSRCENTRY_Link,103637','AP_PAYBILL,FPAYBILLSRCENTRY_Link,103639')
select  * from T_BF_INSTANCESNAPHIS where FCID in ('AP_PAYBILL,FPAYBILLSRCENTRY_Link,103637','AP_PAYBILL,FPAYBILLSRCENTRY_Link,103639')
delete from T_BF_SNAPBACKUP where FCID in ('AP_PAYBILL,FPAYBILLSRCENTRY_Link,103637','AP_PAYBILL,FPAYBILLSRCENTRY_Link,103639')

select * from  T_AP_PAYBILLSRCENTRY where fid in (103637,103639)
delete from T_AP_PAYBILLSRCENTRY_LK where FENTRYID in  (104855,104857)



select * into T_STK_CLOSEPROFILE20191118  from T_STK_CLOSEPROFILE 

delete from T_STK_CLOSEPROFILE where FCLOSEDATE>'2018-12-31 00:00:00.000'
