select *,case t.FSID when not null t.FSID end from 
(select e.*,
lgt.FBILLNO FRBILLNO,lgt.FSEQ FRSEQ, lgt.FRDATE,lgt.FCONTRACTNO,lgt.FTRACKINGNO,lgt.FDECLARATIONNO,lgt.FPRTNAME,
lgt.FRUNITNAME,lgt.FRQTY,lgt.FRCURRENCYNAME,lgt.FRPRICE,lgt.FRAMOUNT,lgt.FRTAMOUNT,lgt.FRCUSTNAME,
lgt.FINSURE,lgt.FBANKNO,lgt.FBANKNAME,lgt.FTRMODE,lgt.FTRTYPE,lgt.FREMARK
from V_QNWB_OUTSTOCKENTITY e
full join V_QNWB_LOGISTICS lgt on e.FSID=lgt.FDELIVERYNOTICE and e.FSTABLENAME='T_SAL_DELIVERYNOTICEENTRY') t
left join T_SAL_DELIVERYNOTICE notice on notice.FID=lk.FSBILLID
left join T_SAL_DELIVERYNOTICEENTRY notice_e on notice_e.FENTRYID=lk.FSID

where t.FRBILLNO is not null

--创建视图V_QNWB_OUTSTOCKENTITY
if (exists (select * from sys.objects where name = 'V_QNWB_OUTSTOCKENTITY'))
    drop view V_QNWB_OUTSTOCKENTITY
go
create view V_QNWB_OUTSTOCKENTITY as 
select e.FENTRYID FID,o.FSALEORGID,o.FBILLNO,e.FSEQ,o.FDATE,o.FCUSTOMERID,o.FSALESMANID,fin.FSETTLECURRID,
e.FMATERIALID,e.FBOMID,e.FUNITID,e.FREALQTY,f.FPRICEUNITID,f.FPRICEUNITQTY,f.FPRICE,f.FTAXPRICE,
f.FAMOUNT,f.FAMOUNT_LC,f.FALLAMOUNT,f.FALLAMOUNT_LC,f.FDISCOUNT,f.FCOSTPRICE,f.FCOSTAMOUNT,f.FCOSTAMOUNT_LC,
r.FSOORDERNO,r.FSOENTRYID,lk.FSTABLENAME,lk.FSBILLID,lk.FSID,
cust.FNUMBER FCUSTNUMBER,cust_l.FNAME FCUSTNAME,saler.FSALENAME,saler.FSALERNUMBER,
mat.FNUMBER FMATNUMBER,mat_l.FNAME FMATNAME,cuy.FSYSMBOL FSETTLECURRSYSMBOL,cuy_l.FNAME FSETTLECURRNAME,
unit1.FNAME FUNITNAME,bom.FNUMBER FBOMNUMBER,unit2.FNAME FPRICEUNITNAME
from T_SAL_OUTSTOCKENTRY e
left join T_SAL_OUTSTOCKENTRY_F f on e.FENTRYID=f.FENTRYID
left join T_SAL_OUTSTOCKFIN fin on e.FID=fin.FID
left join T_SAL_OUTSTOCKENTRY_LK lk on e.FENTRYID=lk.FENTRYID
left join T_SAL_OUTSTOCKENTRY_R r on r.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCK o on o.FID=e.FID
left join T_BD_MATERIAL mat on mat.FMASTERID=e.FMATERIALID
left join T_BD_MATERIAL_L mat_l on mat_l.FMATERIALID=e.FMATERIALID and mat_l.FLOCALEID=2052
left join T_BD_CUSTOMER cust on cust.FCUSTID=o.FCUSTOMERID
left join T_BD_CUSTOMER_L cust_l on cust_l.FCUSTID=o.FCUSTOMERID and cust_l.FLOCALEID=2052
left join T_BD_CURRENCY cuy on cuy.FCURRENCYID=fin.FSETTLECURRID
left join T_BD_CURRENCY_L cuy_l on cuy_L.FCURRENCYID=fin.FSETTLECURRID and cuy_l.FLOCALEID=2052
left join T_BD_UNIT_L unit1 on unit1.FUNITID=e.FUNITID and unit1.FLOCALEID=2052
left join T_ENG_BOM bom on bom.FID=e.FBOMID
left join T_BD_UNIT_L unit2 on unit2.FUNITID=f.FPRICEUNITID and unit2.FLOCALEID=2052

left join --销售员辅助资料
(select e.FENTRYID FSALERID,m.FNUMBER FSALERNUMBER,staff.FNAME as FSALENAME from T_BD_OPERATORENTRY e
left join  T_BD_STAFF_L staff on staff.FSTAFFID=e.FSTAFFID
left join T_BD_STAFF m on m.FSTAFFID=staff.FSTAFFID
where staff.FLOCALEID=2052 and e.FOPERATORTYPE='XSY') saler on saler.FSALERID=o.FSALESMANID
go
