use AIS20190719142428
--创建视图V_QNWB_OUTSTOCKENTITY
if (exists (select * from sys.objects where name = 'V_QNWB_OUTSTOCKENTITY'))
    drop view V_QNWB_OUTSTOCKENTITY
go
create view V_QNWB_OUTSTOCKENTITY as 
select e.FENTRYID FID,o.FSALEORGID,o.FBILLNO,e.FSEQ,o.FDATE,o.FCUSTOMERID,o.FSALESMANID,fin.FSETTLECURRID,
e.FMATERIALID,e.FBOMID,e.FUNITID,e.FREALQTY,f.FPRICEUNITID,f.FPRICEUNITQTY,f.FPRICE,f.FTAXPRICE,
f.FAMOUNT,f.FAMOUNT_LC,f.FALLAMOUNT,f.FALLAMOUNT_LC,f.FDISCOUNT,f.FCOSTPRICE,f.FCOSTAMOUNT,f.FCOSTAMOUNT_LC,
r.FSOORDERNO,r.FSOENTRYID,lk.FSTABLENAME,lk.FSBILLID,lk.FSID
from T_SAL_OUTSTOCKENTRY e
left join T_SAL_OUTSTOCKENTRY_F f on e.FENTRYID=f.FENTRYID
left join T_SAL_OUTSTOCKFIN fin on e.FID=fin.FID
left join T_SAL_OUTSTOCKENTRY_LK lk on e.FENTRYID=lk.FENTRYID
left join T_SAL_OUTSTOCKENTRY_R r on r.FENTRYID=e.FENTRYID
left join T_SAL_OUTSTOCK o on o.FID=e.FID
go



------------------------------------------------------------报关资料视图
if (exists (select * from sys.objects where name = 'V_QNWB_LOGISTICS'))
    drop view V_QNWB_LOGISTICS
go
create view V_QNWB_LOGISTICS as 
select m.FBILLNO,e.FSEQ,
case e.fzone when '0' then '国外' when '1' then '国内' end FZONE,
e.FDELIVERYNOTICE,e.FDATE FRDATE,e.FCONTRACTNO,e.FTRACKINGNO,e.FDECLARATIONNO,e.FPRTNAME,
ul.FNAME FRUNITNAME,e.FQTY FRQTY,cl.FNAME FRCURRENCYNAME,e.FPRICE FRPRICE,e.FAMOUNT FRAMOUNT,e.FTAMOUNT FRTAMOUNT,
e.FCUSTNAME FRCUSTNAME,
case e.FINSURE when '0' then '人保' when '1' then '中信保' end FINSURE,e.FREMARK,
bank.FNUMBER FBANKNO,bl.FNAME FBANKNAME,
mode.FDATAVALUE FTRMODE,ttype.FDATAVALUE FTRTYPE
from T_SAL_QNWB_LogisticsEntity e
left join T_SAL_QNWB_Logistics m on e.FID=m.FID
left join T_BD_UNIT_L  ul on ul.FUNITID=e.FUNITID and ul.FLOCALEID=2052
left join T_BD_CURRENCY_L cl on cl.FCURRENCYID=e.FCURRENCYID and cl.FLOCALEID=2052
left join T_CN_BANKACNT bank on bank.FBANKACNTID=e.FBANKACCT
left join T_CN_BANKACNT_L  bl on  bl.FBANKACNTID=e.FBANKACCT and bl.FLOCALEID=2052
left join --贸易方式辅助资料
(select T1.FMASTERID,T1.FNUMBER,T2.FDATAVALUE from T_BAS_ASSISTANTDATAENTRY T1
                    left join T_BAS_ASSISTANTDATAENTRY_L T2 on T2.FENTRYID = T1.FENTRYID  and T2.FLOCALEID = 2052
                    left join T_BAS_ASSISTANTDATA_L T3 on T3.FID = T1.FID and T3.FLOCALEID = 2052
                    where T3.FNAME ='贸易方式') mode on mode.FMASTERID=e.FTRADEMODE
left join --运输方式辅助资料
(select T1.FMASTERID,T1.FNUMBER,T2.FDATAVALUE from T_BAS_ASSISTANTDATAENTRY T1
                    left join T_BAS_ASSISTANTDATAENTRY_L T2 on T2.FENTRYID = T1.FENTRYID  and T2.FLOCALEID = 2052
                    left join T_BAS_ASSISTANTDATA_L T3 on T3.FID = T1.FID and T3.FLOCALEID = 2052
                    where T3.FNAME ='运输方式') ttype on ttype.FMASTERID=e.FTRANSPORTTYPE

go

select * from V_QNWB_OUTSTOCKENTITY